enabled: false

replicaCount: 3

image:
  repository: registry.w3x.app/w3x/health-frontend
  pullPolicy: IfNotPresent
  tag: "1.0.0"

fullnameOverride: "health-frontend-phc"

serviceAccount:
  create: true
  automount: true

service:
  type: ClusterIP
  port: 80
  targetPort: 3302

ingress:
  enabled: false

autoscaling:
  enabled: false

environments:
  nuxt:
    public:
      apiBaseUrl: "http://health-backend-phc.wenex-client.svc.cluster.local"
