enabled: false

replicaCount: 2

image:
  repository: registry.w3x.app/w3x/ctb-frontend
  pullPolicy: IfNotPresent
  tag: "1.0.0"

fullnameOverride: "ctb-frontend"

serviceAccount:
  create: true
  automount: true

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: false

autoscaling:
  enabled: false

environments:
  nuxt:
    public:
      apiBaseUrl: "http://ctb-backend.wenex-client.svc.cluster.local"
