enabled: false

replicaCount: 3

fullnameOverride: "phc-workers"

serviceAccount:
  create: true
  automount: true

service:
  type: ClusterIP
  port: 80

livenessProbe:
  httpGet:
    path: /status
    port: http
  initialDelaySeconds: 90
  periodSeconds: 30
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /status
    port: http
  initialDelaySeconds: 45
  periodSeconds: 15
  failureThreshold: 3

ingress:
  enabled: false

autoscaling:
  enabled: false
