apiVersion: v2
name: porsyar
description: A Helm chart for Porsyar with PostgreSQL, Redis

type: application

# Helm chart Version
version: 1.0.0

keywords:
  - porsyar
  - postgresql
  - redis

maintainers:
  - name: Porsyar
    email: info@phaicare.com

icon: https://avatars.githubusercontent.com/u/207422183?s=200&v=4

dependencies:
  - name: postgresql
    version: "16.4.16"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: postgresql.enabled
  - name: redis
    version: 20.11.2
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: redis.enabled
