apiVersion: v2
name: phc
description: A Helm chart for Kubernetes

type: application
version: 1.0.4
appVersion: "1.0.4"

dependencies:
  - name: services
    version: 1.0.1
    condition: services.enabled
    repository: file://charts/services
  - name: workers
    version: 1.0.1
    condition: workers.enabled
    repository: file://charts/workers

  - name: assets
    version: 1.0.0
    condition: assets.enabled
    repository: file://charts/assets

  - name: frontend
    version: 1.0.3
    condition: frontend.enabled
    repository: file://charts/frontend

icon: https://avatars.githubusercontent.com/u/207422183?s=200&v=4
