apiVersion: v2
name: phc
description: A Helm chart for Kubernetes

type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: frontend
    version: 1.0.0
    condition: frontend.enabled
    repository: file://charts/frontend

icon: https://avatars.githubusercontent.com/u/207422183?s=200&v=4
