apiVersion: v2
name: phc
description: A Helm chart for Kubernetes

type: application
version: 1.1.6
appVersion: "1.1.0"

dependencies:
  - name: services
    version: 1.1.2
    condition: services.enabled
    repository: file://charts/services
  - name: workers
    version: 1.1.2
    condition: workers.enabled
    repository: file://charts/workers

  - name: assets
    version: 1.1.1
    condition: assets.enabled
    repository: file://charts/assets

  - name: frontend
    version: 1.1.2
    condition: frontend.enabled
    repository: file://charts/frontend

  - name: landing
    version: 1.0.2
    condition: landing.enabled
    repository: file://charts/landing

icon: https://avatars.githubusercontent.com/u/207422183?s=200&v=4
